install.packages("readxl")
library(readxl)
seseds = read_excel("/Users/rdcarini/Documents/Projects/modeling/ModelingAgency/PythonCodes/AdjustedCData.xlsx", sheet = "seseds")
msncodes = read_excel("/Users/rdcarini/Documents/Projects/modeling/ModelingAgency/PythonCodes/AdjustedCData.xlsx", sheet = "msncodes")
both = merge(seseds,msncodes)
summary(both)
write.csv(both, "merged.csv")

btu_energy_data = subset(both,both$Unit=="Billion Btu" | both$Unit=="Million Btu")
summary(btu_energy_data)
write.csv(btu_energy_data, "BtuEnergyData.csv")


california = subset(seseds,seseds$StateCode=="CA")
arizona = subset(seseds,seseds$StateCode=="AZ")
newmexico = subset(seseds,seseds$StateCode=="NM")
texas = subset(seseds,seseds$StateCode=="TX")
write.csv(california, "California_Data.csv")
write.csv(arizona, "Arizona_Data.csv")
write.csv(newmexico, "NewMexico_Data.csv")
write.csv(texas, "Texas_Data.csv")
summary(texas)
summary(seseds$StateCode)
summary(msncodes)
summary(california)
